remote_theme: pages-themes/cayman@v0.2.0 #这里选择你要使用的远程主题
plugins:
- jekyll-remote-theme # 使用远程主题需要引入这个插件
title: Sustamp学习笔记
description: #这里输入你的主页描述
#baseUrl是定义基础路径，个人站点默认是"/"，项目站点则需要在这里设置"/仓库名"。
#这会让基础地址定位成：https://username.github.io/[baseurl]，方便后续的资源访问。
baseurl: "/"  #项目站点设置为"/仓库名"
